### ISSUE TITLE
New project fails to compile

### ISSUE THREAD

**Issue by clartaq** [reagent-project/reagent-frontend-template#9]
After starting a new project with the command `lean new reagent-frontend cljsrte`, the project was created correctly. Attempting to run the new project with `lean figwheel` produced an error stack trace starting with 

```
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
        ...
```

This is on a new iMac running High Sierra and Java 9.04.  FWIW, creating and trying to start a new project with the [Reagent](https://github.com/reagent-project/reagent-template) template produces the same error.

Java 9 modules problem?

**Comment by clartaq** [comment]
Work Around

By adding `:jvm-opts ["--add-modules" "java.xml.bind"]` to the `project.clj` file, it now compiles and runs as expected. Not sure how to make a `project.clj` that will work with both Java 9 and earlier. Maybe a new command line argument to the template.

**Comment by yogthos** [comment]
I'm hoping the issue gets resolved upstream when ClojureScript 1.10 is released. In the meantime, you can also add a dependency `[javax.xml.bind/jaxb-api "2.3.0"]` instead. That should  be compatible with both Java 8 and 9.

**Comment by tirkarthi** [comment]
I think this is fixed in master with https://github.com/reagent-project/reagent-frontend-template/commit/2685110d1ecbfb23653c4815a554047d47a0cd08

**Comment by yogthos** [comment]
Yeah it looks like the issue should be resolved in latest cljs version. I'll close this.

**Comment by clartaq** [comment]
Hmm...

Still doesn't work for me. I saw `lein` download the new template when creating a new project. The `.prj` file includes ClojureScript 1.10.238. Ran `lein figwheel` in the directory of the new project and it failed with the same error.

Running `lein clean && lein package` DID produce a project that compiled without error and could be loaded into a browser successfully.

**Comment by tirkarthi** [comment]
There is an issue in lein-figwheel related to JDK 9 but I am not sure if that is the cause here : https://github.com/bhauman/lein-figwheel/issues/612

**Comment by clartaq** [comment]
Could be. figwheel sidecar is mention about halfway down in the stack trace.

**Comment by yogthos** [comment]
Yeah that sounds like an issue with Figwheel rather than the template. All I can do on my end is update to a newer version once it's available.
